import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";
import {
  ClerkProvider,
} from '@clerk/nextjs';
import { ExitModal } from "@/components/modals/exit-modal";
const font = Nunito({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "CyberKids",
  description: "Generated by create next app",
  icons:"/cyberbot.svg"
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>

      <html lang="en">
        <body className={font.className}>
          <ExitModal />
          {children}
        </body>
      </html>

    </ClerkProvider>
  );
}
